### ISSUE TITLE
Incorrect calculation of buffer size

### ISSUE THREAD

**Issue by matejr** [ripple/ripple-dot-net#14]
In StReader you have
```
private const int Megs8 = 1024*1024*4;
```
but the commit message says "Open StReader.FromFile FileStream with 8MB buffer"

**Comment by sublimator** [comment]
Thanks! Duh

**Comment by matejr** [comment]
Have you measured the most appropriate buffer size? Buffer size looks very large and the buffer will be allocated on the large object heap.

**Comment by sublimator** [comment]
Should probably just leave it to the OS eh? Was experimenting briefly.
Probably shouldn't have committed it. The only use case for the StReader
currently is reading a history pack of around 300MB.

**Comment by sublimator** [comment]
Closed with 436351d

Looking at setting up a Nuget package and getting some kind of proper releasing soon. I'm new to C#/.NET so don't know what's involved yet.
