### ISSUE TITLE
Document the meaning of "Podo"

### ISSUE THREAD

**Issue by matejr** [ripple/ripple-dot-net#18]
Is Podo actually POCO? Plain old CLR object?

**Comment by sublimator** [comment]
I can change it to Poco or maybe just PlainObject ?

SignPoco
SignPlainObject

**Comment by matejr** [comment]
Maybe SignPoco or just SignObject. 

You will probably also need to modify the method contract. 

Current implementation assumes that one provides object that can be serialized to json with Json.net library (method SignPodo uses JObject.FromObject). Json.net has its own assumption about serialization (for example, other serializers might serialize public and non-public fields, but Json.net serializes public fields and public properties). 

However, as soon as one starts modifying serialization (and implements maybe [ISerializable](https://msdn.microsoft.com/en-us/library/system.runtime.serialization.iserializable(v=vs.110).aspx) interface), this class is probably no longer a POCO.

It should be also clear from the contract spec how one should provide values for optional fields.

**Comment by sublimator** [comment]
> It should be also clear from the contract spec how one should provide
values for optional fields.

What do you mean?

**Comment by matejr** [comment]
> What do you mean?

See the following example from my code:

```C#
class UnsignedAcountSetTransaction : IUnsignedAccountSetTransaction
{
	// TransactionType is enum. Will SignPodo serialize it as an integer or as a string?
	public TransactionType TransactionType { get; }
	public string Account { get; set; }

	// How will SignPodo serialize this? As an object or will convert the
	// AmountXrp to string (maybe using ToString method)?
	public AmountXrp Fee { get; set; }

	public uint Sequence { get; set; }
	public string Domain { get; set; }

	// SetFlag is optional in JSON.
	// Can I change this to int? and set it to null if
	// I want this field to be ignored?
	public int SetFlag { get; set; } = 0;

	// MessageKey is optional. What happens
	// when it is null? Will SignPodo ignore
	// this property or set MessageKey in JSON to empty string?
	public string MessageKey { get; set; }
}
```

It should be completely clear from the method contract (specification) how SignPodo handles such POCOs. It is not possible to use just any POCO even if the fields are properly named. This is one reason why this library should include strongly typed classes for unsigned transaction.

**Comment by sublimator** [comment]
Yes, it was just meant for an object comprised of primitives that map
relatively directly to json. Typed transactions are on the cards.

**Comment by sublimator** [comment]
It would probably be best to just get rid of SignPo(c|d)o in the meantime

**Comment by matejr** [comment]
Agreed.
