### ISSUE TITLE
TxFormat.Validate should throw custom exception instead of System.Exception

### ISSUE THREAD

**Issue by matejr** [ripple/ripple-dot-net#21]
It is very hard to differentiate between "serious" exceptions (OutOfMemoryException, AccessViolationException, etc.) and "innocent" validation exceptions.

Throwing System.Exception (and catching them) is against Microsoft [guidelines for developing class libraries](https://msdn.microsoft.com/en-us/library/ms229007(v=vs.100).aspx) anyway. 

> Do not throw System.Exception or System.SystemException.

and 

> Avoid handling errors by catching non-specific exceptions, such as System.Exception, System.SystemException, and so on, in application code. 

.NET already contains [ValidationException](https://msdn.microsoft.com/en-us/library/system.componentmodel.dataannotations.validationexception(v=vs.110).aspx) class. However,  this class is associated with ValidationAttribute and it is probably not the most appropriate for your use case.

**Comment by sublimator** [comment]
Pull request welcome

**Comment by matejr** [comment]
Ok, will do.

**Comment by sublimator** [comment]
Thanks for all your help :)
