### ISSUE TITLE
TxSigner.SignJson should throw an exception when provided secret doesn't match the Json Account property

### ISSUE THREAD

**Issue by matejr** [ripple/ripple-dot-net#30]
This test should throw an exception (probably InvalidTxException) but it doesn't:

```C#
        [TestMethod]
        public void SignJson_AccountDoesntMatchSecret_ThrowsInvalidTxException()
        {
            var signer = TxSigner.FromSecret("snepZK8jifkTMtvaea5xxzSiPJrEn");
            var json = JObject.FromObject(new {
                TransactionType = "Payment",
                // account and secret mismatch
                Account = "rUQTVS1oNpyVodZHAD3gHrLdnZBv7FwUMu",
                Destination = "rEMoUBvGWuBT7LFyZgJmiaofyUALYMc1wp",
                Fee = "100",
                Sequence = 10,
                Amount = "100000",
            });

            var r = signer.SignJson(json);
        }
```

**Comment by sublimator** [comment]
RegularKey

**Comment by matejr** [comment]
What do you mean by RegularKey?

This issue is a regression. If I remember correctly, I was getting an exception when I tried to sign transactions with wrong secret key.

**Comment by matejr** [comment]
I'm closing this issue. Current behaviour probably makes more sense.

**Comment by sublimator** [comment]
Sorry the short reply before. I'm guesing you learned about master vs
regular key etc?

**Comment by sublimator** [comment]
Maybe with older versions of JavaScript ripple-lib re: "I was getting an
exception when I tried to sign transactions with wrong secret key."

But that was considered broken, because it didn't allow use of non master
keys.

**Comment by matejr** [comment]
I knew about master vs. regular key before. I just somehow thought it was a regression and that this library supported signing with master keys only. 

However, it looks like I misinterpreted exception message "Checksum does not validate". I somehow thought it applied to account json property/secret combination (basically mismatch between master key and public key) and not to the checksum in secret itself. 

If I use TxSigner _static_ methods and user mistypes the secret, the library now throws "Checksum does not validate". But from the point of view of developer it is not clear which parameter is problematic (secret or json). I somehow thought it was json's fault because json was problematic in all other cases.

I'll try to fix this and throw exception with message that explicitly uses the word "secret" somewhere (probably ArgumentException with proper message and with inner exception).

**Comment by sublimator** [comment]
Thanks for the polish
