### ISSUE TITLE
Use managed library instead of libsodium.dll

### ISSUE THREAD

**Issue by matejr** [ripple/ripple-dot-net#7]
What is the rationale for using libsodium and managed wrapper?

**Comment by sublimator** [comment]
Can you recommend any suitable, well tested libraries in pure C#? Will certainly consider it.

**Comment by sublimator** [comment]
Would certainly fix #4 :) 

I've been having troubles with the BigDecimal library that this is currently using, and need to replace it so I'm especially conscious at the moment of needing to be careful with library choice.

**Comment by matejr** [comment]
I can't recommend any managed library. My experience is limited to Bouncy Castle, Mono and classes provided by mscorlib.dll. Do you need libsodium.dll just for signing with Ed25519?

**Comment by sublimator** [comment]
Yes, only for ed25519.

I believe unless you actually use an Ed25519 keypair, and use one of the
methods that tries and calls libsodium.dll you can probably ignore it.

Though of course the test suite requires it currently.

I will look further into it, but I am currently looking into the BigDecimal
issue for the iou "value"s

**Comment by sublimator** [comment]
@matejr 

https://github.com/CodesInChaos/Chaos.NaCl  

Thoughts ? 

The nice thing about ed25519 is the sigs are deterministic etc, and it's designed to be hardish to shoot yourself in the foot in terms of implementation. Will look if it tests against http://ed25519.cr.yp.to/python/sign.input

**Comment by sublimator** [comment]
Seems to actually: https://raw.githubusercontent.com/CodesInChaos/Chaos.NaCl/master/Chaos.NaCl.Tests/Ed25519TestVectors.cs

**Comment by sublimator** [comment]
Done with 54f14d21ba3643408f22da28c0dbce1f89996e33
